map: INFERNO
mode: SOLO

enabled: false

# Absolute path to data file. Data file can have any name
data-file: 'C:\Users\robin\Desktop\DewDrop test server\skywars-data.yml'

scoreboard-title: '&bTitle'
scoreboard:
- '&aYou are playing skywars'
- 'Map: {map}'
- 'Mode: {mode}'
- 'Time left: {time}'

kits-rows: 3

kits: # Use this website to generate commands for fancy items: http://mapmaking.fr/give/ - for Player fill in {player}

  0:
    item: GRASS
    data: 0
    name: 'Sample kit'
    lore:
     - This is line 1
     - This is line 2
    commands:
     - 'give {player} stone 32'
     - 'give {player} minecraft:golden_sword 1 0 {display:{Name:"ยง5Sword of Death",Lore:["Some lore","Second line"]},Unbreakable:1,ench:[{id:17,lvl:2},{id:19,lvl:7}]}'
  
  1:
    item: WOOL
    data: 3
    name: 'Second sample kit'
    lore:
     - This is not line 2
     - This is not line 1
    commands:
     - 'give {player} sponge 6'